apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tinymon-operator.fullname" . }}
  labels:
    {{- include "tinymon-operator.labels" . | nindent 4 }}
type: Opaque
data:
  tinymon-url: {{ .Values.tinymon.url | b64enc | quote }}
  tinymon-api-key: {{ .Values.tinymon.apiKey | b64enc | quote }}
