{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tinymon-operator.serviceAccountName" . }}
  labels:
    {{- include "tinymon-operator.labels" . | nindent 4 }}
{{- end }}
